Mist env

diff --git a/mpan-install b/mpan-install
--- a/mpan-install
+++ b/mpan-install
@@ -24160,6 +24160,10 @@ sub as_code {
   package $package_name;
   no warnings;
   my \$_result;
+  use Devel::CheckBin;
+  use Devel::CheckLib;
+  use Devel::CheckCompiler;
+  use Probe::Perl;
   BEGIN { \$_result = Mist::Environment->bind }
   $line_pos; $code;
   sub distinfo { \$_result }
@@ -24185,6 +24189,11 @@ sub parse {
   package DISTRIBUTION;
   no warnings;
   my $_result;
+
+  use Devel::CheckBin;
+  use Devel::CheckLib;
+  use Devel::CheckCompiler;
+  use Probe::Perl;
 
   BEGIN { $_result = Mist::Environment->bind }
 
@@ -24212,7 +24221,7 @@ notest 'Term::ReadKey';
   package CMD_WRAPPER::Bash;
 
   sub get_content {
-    my $content = <<'TEXTFILE_A0EA2897D9BE1A03EA0A30C741D5E8E7';
+    my $content = <<'TEXTFILE_F4BEF06F38018F02838EE37EA3114906';
 #!/bin/bash
 
 # get the absolute path of the executable
@@ -24238,10 +24247,10 @@ if [ $SELF_PATH == $CALL_PATH ] ; then
   exit 1
 fi
 
-# try to upward-find local::lib directory
+# try to upward-find mist directory
 for UPDIR in . .. ../.. ../../.. ../../../.. ; do
-  TEST="$WRAPPER/$UPDIR/perl5";
-  if [ -d $TEST ] ; then
+  TEST="$WRAPPER/$UPDIR/mistfile";
+  if [ -f $TEST ] ; then
       LOCAL_LIB=$( cd -P "$( dirname "$TEST" )" && pwd )
       BASE_DIR="$WRAPPER/$UPDIR"
       break
@@ -24250,13 +24259,13 @@ done
 
 #exit if we can't find any
 if [ ! $LOCAL_LIB ] ; then
-  echo "$0: No local::lib directory found. Abort!" >&2
+  echo "$0: No mistfile found. Abort!" >&2
   exit 1
 fi
 
-exec "$BASE_DIR/perl5/bin/mist-run" `basename $0` "$@"
+exec "$BASE_DIR/mist-run" `basename $0` "$@"
 
-TEXTFILE_A0EA2897D9BE1A03EA0A30C741D5E8E7
+TEXTFILE_F4BEF06F38018F02838EE37EA3114906
     chomp $content;
     return $content;
   }
@@ -24406,9 +24415,9 @@ package Mist::Script::install;
 use strict;
 use warnings;
 use Config;
-use Getopt::Long 2.42;
 our @CMD_OPTS;
 BEGIN { @CMD_OPTS = @ARGV; @ARGV = () }
+use Getopt::Long 2.42;
 our $MPAN_DIST_DIR || die '$MPAN_DIST_DIR not set';
 our $PERL5_BASE_LIB = 'perl5';
 {
@@ -24441,7 +24450,7 @@ my $mpan          = File::Spec->catdir( $Bin, $MPAN_DIST_DIR );
 my $local_lib     = File::Spec->catdir( $mist_home, $LOCAL_LIB_DIR );
 my $libexec_dir   = File::Spec->catdir( $perl5_baselib, 'libexec' );
 mkpath( $libexec_dir );
-my $cmd_wrapper     = File::Spec->catfile( $libexec_dir, 'cmd-wrapper.bash' );
+my $cmd_wrapper = File::Spec->catfile( $libexec_dir, 'cmd-wrapper.bash' );
 {
   my $cmd_wrapper_src = CMD_WRAPPER::Bash->get_content;
   open my $fh, '>', $cmd_wrapper
@@ -24484,12 +24493,17 @@ unless (caller) {
   open my $env, '>', $mist_rc;  # to catch write errors early on
   my $bin_dir = File::Spec->catdir( $p5_dir, 'bin' );
   mkpath( $bin_dir );
-  my $mist_run = File::Spec->catfile( $bin_dir, 'mist-run');
-  open my $wrapper, '>', $mist_run; # to catch write errors early on
+  my $mist_run_fn = File::Spec->catfile( $bin_dir, 'mist-run');
+  open my $mist_run, '>', $mist_run_fn; # to catch write errors early on
   {
-    my $perm = ( stat $mist_run )[2] & 07777;
-    chmod( $perm | 0755, $mist_run );
+    my $perm = ( stat $mist_run_fn )[2] & 07777;
+    chmod( $perm | 0755, $mist_run_fn );
   }
+  print $mist_run <<'BASH';
+#!/bin/bash
+echo "Mist environment not correctly installed"
+exit 1'
+BASH
   local $ENV{HOME} = $workspace;
   if ( eval { DISTRIBUTION->distinfo->can( 'get_assertions' ) }) {
     $_->() for DISTRIBUTION->distinfo->get_assertions;
@@ -24498,8 +24512,12 @@ unless (caller) {
   my @notest  = ( @$DONT_TEST_DISTS );
   my @prereqs = ( @$PREREQUISITE_DISTS );
   run_cpanm( $_ ) for @prepend;
-  run_cpanm( '--installdeps', @notest ) if @notest;
-  run_cpanm( '--notest',      @notest ) if @notest;
+  for my $module ( @notest ) {
+    # in some wired cases, two modules depending on each other fail
+    # so we have to build them one by one to ensure correct order
+    run_cpanm( '--installdeps', $module );
+    run_cpanm( '--notest',      $module );
+  }
   run_cpanm( @prereqs ) if @prereqs;
   printf $env <<'MIST_ENV', $mist_home;
 # This file is automatically generated by ./mpan-install
@@ -24516,7 +24534,9 @@ MIST_ENV
     print $env local::lib->environment_vars_string_for( "${local_lib}" );
   }
   close $env;
-  printf $wrapper <<'WRAPPER', $mist_home, $mist_rc;
+  close $mist_run;
+  open $mist_run, '>', $mist_run_fn; # reopen mist-run and flesh it out
+  printf $mist_run <<'WRAPPER', $mist_home, $mist_rc;
 #!/bin/bash
 MIST_ROOT="%s"
 MIST_ENV="%s"
@@ -24539,6 +24559,8 @@ export PATH="$MIST_ROOT/bin:$MIST_ROOT/sbin:$MIST_ROOT/script:$PATH"
 export PERL5LIB="$MIST_ROOT/lib:$PERL5LIB"
 mist_exec "${@}"
 WRAPPER
+  unlink File::Spec->catfile( $mist_home, 'mist-run' );
+  symlink $mist_run_fn, File::Spec->catfile( $mist_home, 'mist-run' );
   for my $script_dir (qw/ bin sbin script /) {
     my $loc_script_dir = File::Spec->catdir( $perl5_baselib, $script_dir );
     my @binaries;
@@ -24578,36 +24600,37 @@ To enable it put the following line in your scripts:
   source $mist_rc
 To run binaries from this distribution (\$HOME/bin and \$HOME/sbin are in
 automatically prepended to \$PATH) you can also use this wrapper script:
-  $mist_run my_script.pl [OPTIONS ..]
+  $mist_run_fn my_script.pl [OPTIONS ..]
 SUCCESS
 }
 ; BEGIN {$MPAN_DIST_DIR = 'mpan-dist';
 ;
 $PREREQUISITE_DISTS = [
-                        'App::Cmd',
-                        'App::cpanminus~1.7',
-                        'CPAN::Meta~2.132830',
-                        'CPAN::PackageDetails',
-                        'CPAN::ParseDistribution',
-                        'Capture::Tiny',
-                        'Devel::CheckBin',
-                        'Devel::CheckCompiler',
-                        'Devel::CheckLib',
-                        'Digest::MD5',
-                        'File::Find::Upwards',
-                        'File::HomeDir',
-                        'File::Share',
-                        'Getopt::Long~2.42',
-                        'List::MoreUtils',
-                        'Minilla~v0.11.0',
-                        'Module::CPANfile~1.0002',
-                        'Module::Path',
-                        'Moo',
-                        'MooX::HandlesVia',
-                        'MooX::late',
-                        'Path::Class',
-                        'Probe::Perl',
-                        'local::lib~2.00'
-                      ];
+  'App::Cmd',
+  'App::cpanminus~1.7',
+  'CPAN::Meta~2.132830',
+  'CPAN::PackageDetails',
+  'CPAN::ParseDistribution',
+  'Capture::Tiny',
+  'Devel::CheckBin',
+  'Devel::CheckCompiler',
+  'Devel::CheckLib',
+  'Digest::MD5',
+  'File::Find::Upwards',
+  'File::HomeDir',
+  'File::Share',
+  'Getopt::Long~2.42',
+  'List::MoreUtils',
+  'Minilla~v0.11.0',
+  'Module::CPANfile~1.0002',
+  'Module::Path',
+  'Moo',
+  'MooX::HandlesVia',
+  'MooX::late',
+  'Path::Class',
+  'Probe::Perl',
+  'Software::License',
+  'local::lib~2.00'
+];
 ;
 };  BEGIN{ __mist::no_thanks( 'Mist::Script::install' ) } };
