Seems to be a working modularized version

diff --git a/mpan-install b/mpan-install
--- a/mpan-install
+++ b/mpan-install
@@ -21310,11 +21310,110 @@ our $VERSION = 1;
 
 1;
 package                         # hide from CPAN
-  App::Mist::MPAN::perlenv;
+  App::Mist::MPAN::perl;
 
-our $VERSION = 1;
+our $PERLBREW_ROOT;
+our $PERLBREW_DEFAULT_VERSION // die '$PERL5_DEFAULT_VERSION not set';
+
+use FindBin ();
+use File::Spec ();
+use Getopt::Long;
+
+my $tmp_base_dir = File::Spec->catdir( $FindBin::Bin, 'tmp' );
+$tmp_base_dir = File::Spec->catdir(
+  File::Spec->tmpdir, ( File::Spec->splitdir( $FindBin::Bin ))[ -1 ]
+  ) unless -d $tmp_base_dir and -w $tmp_base_dir;
+
+my $pb_root    = $ENV{PERLBREW_ROOT} || $PERLBREW_ROOT;
+my $pb_home    = File::Spec->catdir( $tmp_base_dir, 'perlbrew' );
+
+GetOptions( "perl=s" => \ my $pb_version );
+$pb_version ||= $PERLBREW_DEFAULT_VERSION;
+
+print "Using perlbrew root $pb_root\n";
+print "Using temporary perlbrew home $pb_home\n";
+
+my $pb_exec = qx{ which perlbrew } || "${pb_root}/bin/perlbrew";
+chomp $pb_exec;
+
+system( "$pb_exec version >/dev/null" ) == 0 or die <<"MSG";
+No local installation of perlbrew was found ($?). You can install it
+as root via:
+  export PERLBREW_ROOT=${pb_root}
+  curl -kL http://install.perlbrew.pl | sudo -E bash
+or just for this account simply via:
+  curl -kL http://install.perlbrew.pl | bash
+MSG
+
+my @pb_installed_versions = qx# bash -c '
+    export PERLBREW_ROOT=${pb_root}
+    export PERLBREW_HOME=${pb_home}
+
+    if ( ! . \${PERLBREW_ROOT}/etc/bashrc ) ; then
+      perlbrew init 2>/dev/null
+      if ( ! . \${PERLBREW_ROOT}/etc/bashrc ) ; then
+        echo "Cannot create perlbrew environment in \${PERLBREW_ROOT}"
+        exit 127
+      fi
+    fi
+
+    $pb_exec list
+  '#;
+
+my ( $pb_installed ) = grep{ / \b $pb_version \b /x } @pb_installed_versions;
+die "FATAL: $pb_version not found and can't write to $pb_root\n" .
+  "Try\n  sudo -E perlbrew install $pb_version\nto install it as root\n"
+  unless $pb_installed or -w $pb_root;
+
+my @pb_call = ( $pb_exec, 'install', $pb_version );
+system( @pb_call ) == 0 or die "`@pb_call` failed" unless $pb_installed;
+
+if ( !$ENV{PERLBREW_PERL} or $ENV{PERLBREW_PERL} ne $pb_version ) {
+  print "Restarting $0 under $pb_version\n\n";
+  $ENV{PERLBREW_ROOT} = $pb_root;
+  $ENV{PERLBREW_HOME} = $pb_home;
+  exec $pb_exec, 'exec', '--with', $pb_version, $0;
+}
+
+sub write_env {
+  my $env = shift;
+
+# FIXME:      printf $env <<'PERLBREW_HOME', $pb_home;
+# FIXME:  # Initializing perlbrew environment
+# FIXME:
+# FIXME:  if [[
+# FIXME:    -w "$MIST_APP_ROOT/tmp/perlbrew" ||
+# FIXME:    ( -w "$MIST_APP_ROOT/tmp" && ! -e "$MIST_APP_ROOT/tmp/perlbrew" )
+# FIXME:  ]] ; then
+# FIXME:    export PERLBREW_HOME="$MIST_APP_ROOT/tmp/perlbrew"
+# FIXME:  else
+# FIXME:    export PERLBREW_HOME="%%s"
+# FIXME:  fi
+# FIXME:  PERLBREW_HOME
+
+    printf $env <<'PERLBREW_RC', $pb_root, $pb_version;
+
+PERLBREW_DEFAULT_ROOT=%s
+PERLBREW_DEFAULT_VERSION=%s
+
+if [ "x$PERLBREW_ROOT" == "x" ] ; then
+  export PERLBREW_ROOT=$PERLBREW_DEFAULT_ROOT
+fi
+
+source "$PERLBREW_ROOT/etc/bashrc"
+
+perlbrew use $PERLBREW_DEFAULT_VERSION
+
+PERLBREW_RC
+
+}
 
 1;
+
+BEGIN {
+  $PERLBREW_ROOT            = '/opt/perl5';
+  $PERLBREW_DEFAULT_VERSION = 'perl-5.14.2';
+}
 package                         # hide from CPAN
   App::Mist::MPAN::install;
 
@@ -21356,16 +21455,12 @@ copy( $cmd_wrapper_src, $cmd_wrapper )
 my $perm = ( stat $cmd_wrapper )[2] & 07777;
 chmod( $perm | 0755, $cmd_wrapper );
 
-my $pb_root;
-my $pb_home;
-my $pb_version;
-
 {
   # only try to load App::Mist::MPAN::perlenv if it hasn't been
   # compiled in above
   no strict 'refs';
   require App::Mist::MPAN::perlenv
-    unless keys %{ "App::Mist::MPAN::perlenv::" };
+    unless keys %{ "App::Mist::MPAN::perl::" };
 }
 
 App::Mist::MPAN::perlenv->init
@@ -21459,30 +21554,9 @@ export PATH="$MIST_APP_ROOT/bin:$MIST_APP_ROOT/sbin:$MIST_APP_ROOT/script:$PATH"
 
 MIST_ENV
 
-  if ( $pb_version ) {
-# FIXME:      printf $env <<'PERLBREW_HOME', $pb_home;
-# FIXME:  # Initializing perlbrew environment
-# FIXME:
-# FIXME:  if [[
-# FIXME:    -w "$MIST_APP_ROOT/tmp/perlbrew" ||
-# FIXME:    ( -w "$MIST_APP_ROOT/tmp" && ! -e "$MIST_APP_ROOT/tmp/perlbrew" )
-# FIXME:  ]] ; then
-# FIXME:    export PERLBREW_HOME="$MIST_APP_ROOT/tmp/perlbrew"
-# FIXME:  else
-# FIXME:    export PERLBREW_HOME="%%s"
-# FIXME:  fi
-# FIXME:  PERLBREW_HOME
-
-    print $env <<"PERLBREW_RC";
-
-export PERLBREW_ROOT="$pb_root"
-source "$pb_root/etc/bashrc"
-
-perlbrew switch $pb_version
-
-PERLBREW_RC
-  }
+  App::Mist::MPAN::perl->write_env( $env ) if $pb_version;
   require local::lib;
+
   {
     local $SIG{__WARN__} = sub{};
     print $env local::lib->environment_vars_string_for( "${local_lib}" );
@@ -21563,6 +21637,7 @@ automatically prepended to \$PATH) you can also use this wrapper script:
 
 SUCCESS
 }
+
 BEGIN {
   $PERL5_BASE_LIB     = 'perl5';
   $MPAN_DIST_DIR      = 'mpan-dist';
